# Generated by Django 5.1.4 on 2024-12-29 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=32, verbose_name='Make')),
                ('model', models.CharField(max_length=32, verbose_name='Model')),
                ('category', models.CharField(max_length=32, verbose_name='Category')),
                ('priceperday', models.CharField(max_length=32, verbose_name='Price per day')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Reservation start date')),
                ('end_date', models.DateTimeField(verbose_name='Reservation end date')),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='cars.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
