# Generated by Django 5.1.4 on 2024-12-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='priceperday',
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price per day'),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Sport', 'Sport')], max_length=32, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Ford', 'Ford'), ('BMW', 'BMW'), ('Lexus', 'Lexus'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Kia', 'Kia'), ('Nissan', 'Nissan'), ('Volkswagen', 'Volkswagen'), ('Tesla', 'Tesla'), ('Volvo', 'Volvo')], max_length=32, verbose_name='Make'),
        ),
    ]
