# Generated by Django 5.1.4 on 2024-12-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Car',
            new_name='car',
        ),
    ]
